ALTER TABLE services ADD COLUMN IF NOT EXISTS priority INTEGER DEFAULT 0;
ALTER TABLE why_choose_us_cards ADD COLUMN IF NOT EXISTS priority INTEGER DEFAULT 0;
ALTER TABLE integrations ADD COLUMN IF NOT EXISTS priority INTEGER DEFAULT 0;
